<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Department extends Model
{
    use HasFactory;

    public static $department_list = [
        1 => 'Akademik',
        2 => 'AR-GE',
        3 => 'Arşiv/Dokümantasyon',
        4 => 'Bakım/Onarım',
        5 => 'Bilgi İşlem',
        6 => 'Depo/Antrepo',
        7 => 'Eğitim',
        8 => 'Genel Başvuru',
        9 => 'Güvenlik',
        10 => 'Haberleşme',
        11 => 'Halkla İlişkiler',
        12 => 'Hizmet',
        13 => 'Hukuk',
        14 => 'İdari İşler',
        15 => 'İnsan Kaynakları',
        16 => 'İş Geliştirme',
        17 => 'İthalat/İhracat',
        18 => 'Kalite',
        19 => 'Lojistik',
        20 => 'Mimarlık',
        21 => 'Muhasebe',
        22 => 'Mühendislik',
        23 => 'Müşteri Hizmetleri/ÇağrıMerkezi',
        24 => 'Müşteri İlişkileri',
        25 => 'Mütercim Tercümanlık',
        26 => 'Nakliye',
        27 => 'Operasyon',
        28 => 'Organizasyon',
        29 => 'Pazar Araştırma',
        30 => 'Pazarlama',
        31 => 'Personel',
        32 => 'Planlama',
        33 => 'Reklam',
        34 => 'Sağlık',
        35 => 'Satınalma',
        36 => 'Satış',
        37 => 'Sekreterya',
        38 => 'Spor',
        39 => 'Tasarım/Grafik',
        40 => 'Taşıma',
        41 => 'Teknikerlik',
        42 => 'Teknisyenlik',
        43 => 'Turizm',
        44 => 'Ulaştırma',
        45 => 'Üretim/İmalat',
        46 => 'Yönetim',
        47 => 'Finans',
        48 => 'Teknik',
        49 => 'Denetim/Teftiş',
        50 => 'Yiyecek ve İçecek',
        51 => 'Kredi',
        52 => 'Sigorta',
        53 => 'Ruhsatlandırma',
        54 => 'Program',
        55 => 'Teknoloji',
        56 => 'Dış İlişkiler',
        57 => 'Tedarik Yönetimi',
        58 => 'Sistem',
        59 => 'Risk Yönetimi',
        60 => 'Diğer',
        61 => 'Analiz/Araştırma',
        62 => 'Bireysel Portföy Yönetimi Hizmetleri',
        63 => 'Borsa',
        64 => 'Borsa Finans',
        65 => 'Dış Denetim',
        66 => 'Hazineve Sabit Getirili Menkul Değerler',
        67 => 'İç Denetim',
        68 => 'Kurumsal Finansman',
        69 => 'Uluslararası Sermaye Piyasaları',
        70 => 'Varlık Yönetimi',
        71 => 'Yurtiçi Sermaye Piyasaları',
        72 => 'Gayrimenkul Değerleme',
        73 => 'Ön Büro',
        74 => 'Satış ve Pazarlama',
        75 => 'Bilgi Teknolojileri/IT',
        76 => 'TeknikServis',
        77 => 'Pazarlama Teknolojileri',
        78 => 'DijitalPazarlama',
        79 => 'İşSağlığıveGüvenliği',
        80 => 'Parça',
        81 => 'MüşteriHizmetleri',
        82 => 'Satış Geliştirme',
        83 => 'E-Ticaret',
    ];
}
