<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class EmployeeUserForeignLanguage extends Model
{
    use HasFactory;

    protected $table = 'employee_user_foreign_languages';

    public static $languages_list = [
        1 => "Afrikaans",
        2 => "Albanian",
        3 => "Amharic",
        4 => "Arabic",
        5 => "Aragonese",
        6 => "Armenian",
        7 => "Asturian",
        8 => "Azerbaijani",
        9 => "Basque",
        10 => "Belarusian",
        11 => "Bengali",
        12 => "Bosnian",
        13 => "Breton",
        14 => "Bulgarian",
        15 => "Catalan",
        16 => "Central Kurdish",
        17 => "Chinese",
        18 => "Chinese (Hong Kong)",
        19 => "Chinese (Simplified)",
        20 => "Chinese (Traditional)",
        21 => "Corsican",
        22 => "Croatian",
        23 => "Czech",
        24 => "Danish",
        25 => "Dutch",
        26 => "English",
        27 => "English (Australia)",
        28 => "English (Canada)",
        29 => "English (India)",
        30 => "English (New Zealand)",
        31 => "English (South Africa)",
        32 => "English (United Kingdom)",
        33 => "English (United States)",
        34 => "Esperanto",
        35 => "Estonian",
        36 => "Faroese",
        37 => "Filipino",
        38 => "Finnish",
        39 => "French",
        40 => "French (Canada)",
        41 => "French (France)",
        42 => "French (Switzerland)",
        43 => "Galician",
        44 => "Georgian",
        45 => "German",
        46 => "German (Austria)",
        47 => "German (Germany)",
        48 => "German (Liechtenstein)",
        49 => "German (Switzerland)",
        50 => "Greek",
        51 => "Guarani",
        52 => "Gujarati",
        53 => "Hausa",
        54 => "Hawaiian",
        55 => "Hebrew",
        56 => "Hindi",
        57 => "Hungarian",
        58 => "Icelandic",
        59 => "Indonesian",
        60 => "Interlingua",
        61 => "Irish",
        62 => "Italian",
        63 => "Italian (Italy)",
        64 => "Italian (Switzerland)",
        65 => "Japanese",
        66 => "Kannada",
        67 => "Kazakh",
        68 => "Khmer",
        69 => "Korean",
        70 => "Kurdish",
        71 => "Kyrgyz",
        72 => "Lao",
        73 => "Latin",
        74 => "Latvian",
        75 => "Lingala",
        76 => "Lithuanian",
        77 => "Macedonian",
        78 => "Malay",
        79 => "Malayalam",
        80 => "Maltese",
        81 => "Marathi",
        82 => "Mongolian",
        83 => "Nepali",
        84 => "Norwegian",
        85 => "Norwegian Bokmål",
        86 => "Norwegian Nynorsk",
        87 => "Occitan",
        88 => "Oriya",
        89 => "Oromo",
        90 => "Pashto",
        91 => "Persian",
        92 => "Polish",
        93 => "Portuguese",
        94 => "Portuguese (Brazil)",
        95 => "Portuguese (Portugal)",
        96 => "Punjabi",
        97 => "Quechua",
        98 => "Romanian",
        99 => "Romanian (Moldova)",
        100 => "Romansh",
        101 => "Russian",
        102 => "Scottish Gaelic",
        103 => "Serbian",
        104 => "Serbo",
        105 => "Shona",
        106 => "Sindhi",
        107 => "Sinhala",
        108 => "Slovak",
        109 => "Slovenian",
        110 => "Somali",
        111 => "Southern Sotho",
        112 => "Spanish",
        113 => "Spanish (Argentina)",
        114 => "Spanish (Latin America)",
        115 => "Spanish (Mexico)",
        116 => "Spanish (Spain)",
        117 => "Spanish (United States)",
        118 => "Sundanese",
        119 => "Swahili",
        120 => "Swedish",
        121 => "Tajik",
        122 => "Tamil",
        123 => "Tatar",
        124 => "Telugu",
        125 => "Thai",
        126 => "Tigrinya",
        127 => "Tongan",
        128 => "Turkish",
        129 => "Turkmen",
        130 => "Twi",
        131 => "Ukrainian",
        132 => "Urdu",
        133 => "Uyghur",
        134 => "Uzbek",
        135 => "Vietnamese",
        136 => "Walloon",
        137 => "Welsh",
        138 => "Western Frisian",
        139 => "Xhosa",
        140 => "Yiddish",
        141 => "Yoruba",
        142 => "Zulu"
    ];

    public static $language_level_list = [
        1 => 'Başlangıç',
        2 => 'Temel',
        3 => 'Orta',
        4 => 'İyi',
        5 => 'İleri',
    ];
}
